In [1]:
import pandas as pd
import requests

# Manager ID and Gameweek
manager_id = 1873280
GW = 9
# API URL to get the manager's team for a specific Gameweek
url = f"https://fantasy.premierleague.com/api/entry/{manager_id}/event/{GW}/picks/"

# Make the API request to get the manager's team
r = requests.get(url)
data = r.json()

# Create a list of dictionaries to store 'picks' along with metadata
picks_data = data.get('picks', [])  # Ensure 'picks' data is available

# Extract metadata
active_chip = data.get('active_chip')
automatic_subs = data.get('automatic_subs')
entry_history = data.get('entry_history')

# Create a list with metadata for each 'picks' element
data_list = []
for pick in picks_data:
    data_list.append({
        'active_chip': active_chip,
        'automatic_subs': automatic_subs,
        'entry_history': entry_history,
        **pick,  # Include the 'picks' data
    })

# Convert the list of dictionaries to a DataFrame
manager = pd.DataFrame(data_list)

In [3]:
manager

,active_chip,automatic_subs,entry_history,element,position,multiplier,is_captain,is_vice_captain
0,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",230,1,1,False,False
1,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",519,2,1,False,False
2,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",36,3,1,False,False
3,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",311,4,1,False,False
4,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",430,5,1,False,False
5,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",19,6,1,False,False
6,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",52,7,1,False,False
7,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",516,8,1,False,True
8,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",308,9,1,False,False
9,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",355,10,2,True,False
10,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",60,11,1,False,False
11,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",28,12,0,False,False
12,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",403,13,0,False,False
13,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",139,14,0,False,False
14,wildcard,[],"{'event': 9, 'points': 84, 'total_points': 483...",466,15,0,False,False